language: ruby

rvm:
        - 2.4.0

addons:
        postgresql: '9.6'

notifications:
        email: false

env:
        global:
                - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
                - CC_TEST_REPORTER_ID=8d43ae3a928f18aabb5a98065fd25344195b0bd414f8136f3a714b469291ac8a

before_install: 
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
        - sudo locale-gen --no-archive es_CO.UTF-8
        - sudo /etc/init.d/postgresql stop
        - sudo /etc/init.d/postgresql start 9.6
        - psql -c 'CREATE DATABASE sivel2des_pru;' -U postgres
        - bundle install
        - cp config/database.travis.yml config/database.yml
        - cp config/application.rb.plantilla config/application.rb
        - cp config/routes.rb.plantilla config/routes.rb
        - cp config/initializers/sip.rb.plantilla config/initializers/sip.rb
        - cp db/structure.sql db/structure.sql.copia # travis no soporta PostreSQL 10
        - sed -e 's/provider = libc,//g' db/structure.sql.copia > db/structure.sql 
        - bundle exec rails db:setup
        - bundle exec rails sip:indices

script: 
        - bundle exec rails test -b

after_script:
        - ./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT

